Repository status-im/airbyte-custom-connector, pull requests merged in 2025-06, with the labels that each got.

#28 Twitter ads - connector to fetch data from the Ads API
  .gitignore
  README.md
  source-twitter-ads/Dockerfile
  source-twitter-ads/README.md
  source-twitter-ads/main.py
  source-twitter-ads/metadata.yaml
  source-twitter-ads/requirements.txt
  source-twitter-ads/sample_files/config-example.json
  source-twitter-ads/sample_files/configured_catalog.json
  source-twitter-ads/setup.py
  source-twitter-ads/source_twitter_ads/__init__.py
  source-twitter-ads/source_twitter_ads/run.py
  source-twitter-ads/source_twitter_ads/schemas/account.json
  source-twitter-ads/source_twitter_ads/schemas/advertisement_campaign.json
  source-twitter-ads/source_twitter_ads/schemas/promoted_tweet_active.json
  source-twitter-ads/source_twitter_ads/schemas/promoted_tweet_billing.json
  source-twitter-ads/source_twitter_ads/schemas/promoted_tweet_engagement.json
  source-twitter-ads/source_twitter_ads/source.py
  source-twitter-ads/source_twitter_ads/spec.yaml
  source-twitter-ads/source_twitter_ads/stream.py
Labels: bug, connector

#36 youtube: new custom connector
  source-youtube-fetcher/Dockerfile
  source-youtube-fetcher/README.md
  source-youtube-fetcher/main.py
  source-youtube-fetcher/metadata.yaml
  source-youtube-fetcher/requirements.txt
  source-youtube-fetcher/sample_files/config-example.json
  source-youtube-fetcher/sample_files/configured_catalog.json
  source-youtube-fetcher/setup.py
  source-youtube-fetcher/source_youtube_fetcher/__init__.py
  source-youtube-fetcher/source_youtube_fetcher/run.py
  source-youtube-fetcher/source_youtube_fetcher/schemas/channel.json
  source-youtube-fetcher/source_youtube_fetcher/schemas/videos.json
  source-youtube-fetcher/source_youtube_fetcher/source.py
  source-youtube-fetcher/source_youtube_fetcher/spec.yaml
  source-youtube-fetcher/source_youtube_fetcher/utils.py
Labels: connector

#38 discord_message: change start_date
  source-discord-fetcher/source_discord_fetcher/source.py
  source-discord-fetcher/source_discord_fetcher/spec.yaml
Labels: bug
